name: CI/CD Vzeta

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Esto corre en los servidores de GitHub (CI)
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Login en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir y Subir Imagen
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}//mi-app-nginx:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
    - name: Desplegar Contenedor localmente
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/mi-app-nginx:latest
        docker stop mi-web || true
        docker rm mi-web || true
        
        # Crear la carpeta para la persistencia en tu usuario local de la VM
        mkdir -p $HOME/web_data
        
        # Correr con Bind Mount
        docker run -d --name mi-web -p 80:80 -v $HOME/web_data:/usr/share/nginx/html ${{ secrets.DOCKER_USERNAME }}/mi-app-nginx:latest
