name: CI/CD VZeta Examen Transversal


on:
  push:
    branches: [ "main" ] # Se activa automáticamente con cada push a la rama principal

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código de tu repositorio de GitHub
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configura el motor de compilación Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Inicia sesión en Docker Hub de manera segura usando tus Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Compila y sube la imagen de la Aplicación Web (myapp_container)
      - name: Build and Push Web App Image
        uses: docker/build-push-action@v5
        with:
          context: ./app  # Ruta donde está tu Dockerfile de la aplicación
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vzeta-app:latest

      # 5. Compila y sube la imagen de Nginx Reverse Proxy (mynginx_container)
      - name: Build and Push Nginx Proxy Image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx  # Ruta donde está tu archivo nginx.conf y su Dockerfile
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vzeta-nginx:latest
